name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:       
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install

      - name: Substitute API URL
        run: sed -i "s|\${PRIVATE_API_URL}|${PRIVATE_API_URL}|g" web/src/app/services/formulario.service.ts
      

      - name: Build Angular app
        run: npm run build   

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: copying files to S3
        run: |
            aws s3 sync dist/techman-landing-page/browser/ s3://techman.sh --delete