name: Deploy to S3
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:       
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
           
      - name: List files in the current directory
        run: ls -l
      
      - name: Print current working directory
        run: pwd
      
      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod        

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: copying files to S3
        run: |
            aws s3 sync web/dist/ s3://techman.sh --delete